### ISSUE TITLE
Forbidden resource with multiple instances

### ISSUE THREAD

**Issue by yqshao** [c3se/bc_tensorboard#1]
I see reports of (and repoduced) **Forbidden Resource** when multiple tensorbord instances openned; the first would connect but the rest would not. I think it's related to how cookies are generated by injecting the script with hard coded variables: [here](https://github.com/c3se/bc_tensorboard/blob/9484ad14027cef99b8bc8d9085019a7d80c28bc0/view.html.erb#L12-L24). In the case of multiple instances only the last would be in effect.

**Comment by yqshao** [comment]
As a hind sight... this looks like fixed in the upstream's recent cleaup (in a different way): https://github.com/stanford-rc/sh_ood-apps/commit/d50e7c36971768b484f7fe2c296e271a9836baaf

**Comment by Micket** [comment]
I don't understand how that can work. With multiple panels, isn't that setting document.cookie multiple times?

**Comment by yqshao** [comment]
I think `document.coockie=` acts like a "setter" that **adds/modifies** a cookie. If one 
`console.log(document.coockie)` (which reads the available cookies in this document), one see the cookies for all the sessions together, so they are appended not replaced.
